### ISSUE TITLE
[Epic] DynamoDB support

### ISSUE THREAD

**Issue by Blankll** [geek-fun/dockit#142]
## features
As a NoSQL Desktop client, DocKit should be able to connect to DynamoDB, create/edit DynamoDB queries, etc.

### new connection
- [ ] When the user clicks `Add New Connection`, the popup page should list a new item DynamoDB with the logo
- [ ] When the user clicks DynamoDB, it should route to the new DynamoDB connection page to let the user input connection info for DynamoDB
- [ ] Implement DynamoDB connection page to input, verify, and store MongoDB connection info
- [ ] After the user clicks confirm, the DynamoDB connection should be listed in the connection list with the other connections together, connections are differentiated by their name and logos 

### connections manage
- [ ] implement edit connection for DynamoDB
- [ ] implement remove connection for DynamoDB

### Scan/Query views
- [ ] refer to the AWS official solution, build UI facing add data View for user to add new data quickly
![image](https://github.com/user-attachments/assets/c1ee0d21-3f22-40b3-afcb-81c3867497d2)

- [ ] refer to the AWS official solution, build UI facing Scan/Query view for user to access data quickly
![image](https://github.com/user-attachments/assets/9f94bb5d-75e5-46f0-a510-3386b92dfe18)

### Patial SQL query editor
- [ ] Create a new DynamoDB query editor based on monaco-editor
- [ ] When the user clicks to connect the DynamoDB instance, the DynamoDB query editor should show in the right panel with some useful sample queries

### auto-completion
- TBC

**Comment by ChenChunShenG19** [comment]
picked up
