### ISSUE TITLE
[FEATURE] Miscellaneous  tasks for user experience improvement

### ISSUE THREAD

**Issue by Blankll** [geek-fun/dockit#150]
## tasks
- [x] issue that the editor only renders when entering input
- [x] cursor should point to the start of the current action when the user clicks auto-indent
- [x] When a new request result displays, the cursor should point to the first line
- [x] editor comment line, comment selected block with shortcut
- [ ] issue that the editor does not auto-change the theme
- [x] autosave file content
- [ ] configurable font size
- [x] new version detect, the download link change to official download page
