### ISSUE TITLE
multiple files support 

### ISSUE THREAD

**Issue by Blankll** [geek-fun/dockit#16]
tasks:
- [x] toolbar can open folders,
- [x]  toolbar create folders, 
- [x] toolbar delete folder, 
- [x]  create new files in the current folder,
- [x]  delete files
- [x] panel lists all folders, and files in the selected folder
- [ ]

**Comment by Blankll** [comment]
not seen the value of adding  this feature so far, close it

**Comment by Blankll** [comment]
reopen for real user value
