### ISSUE TITLE
configuration for AIGC

### ISSUE THREAD

**Issue by Blankll** [geek-fun/dockit#34]
allow user to config their own openai api token, prompts in the configuration page

- [x] Add an AI section in the configure panel
- [x] Able to configure the openai key and store it locally
- [x] The key data need to be encrypted before store to the host
- [x] user can update the key as well
