### ISSUE TITLE
dockit chat UI

### ISSUE THREAD

**Issue by Blankll** [geek-fun/dockit#35]
user able to trigger a dockit chat panel like GitHub copilot chat, and interact with configured ai model

AC:
- [ ] tool box column in right side created
- [ ] toggle dockit chat box by clicking the logo
- [ ] send message box
- [ ] send button and click send button the message will send out
- [ ] received message are shown in scrollable box with will formated display
